name: GitHub Actions Demo

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - run: echo node -v
